### ISSUE TITLE
Adding substances/materials and they are not saving to my product

### ISSUE THREAD

**Issue by esvisco** [HPDCollaborative/builder23review#3]
There are 2 bugs I found here.

1. When I add a substance in section 2 (substances and materials) it does not show up in the list of added substances - for example I added several substances to my material and they are not listing here. I also tried to go back to the material under section2 (nested materials) and it says the materials do not contain CAS numbers still.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/85577658/174202124-a9daa4f3-b87a-4863-80b6-2792e5538279.png">

3. When I add a material exemption in section 2 (substances and materials) it shows up but is not editable and blank

<img width="662" alt="image" src="https://user-images.githubusercontent.com/85577658/174202088-4351eee4-4240-4077-ae79-0b148a2e0c14.png"><img width="887" alt="image" src="https://user-images.githubusercontent.com/85577658/174202031-976f6721-4477-4628-b21c-ef0e8e5786fd.png">

**Comment by esvisco** [comment]
https://www.loom.com/share/89876c8330e54f1187060e036eb367c2

**Comment by ChantalLavigne** [comment]
@secondmanveran 
I'm also having this problem.

**Comment by Elixir-Tara** [comment]
Same problem here.

**Comment by secondmanveran** [comment]
I am not able to reproduce this error when adding substances, neither locally or on the stage.

I did encounter an error in the Material form request, which was fixed and now I can save a material just fine.

Please make sure your browser is up to date for whatever browser you use.

```
Tested in Brave: Version 1.40.107 Chromium: 103.0.5060.53
Chrome: Version 103.0.5060.53 (Official Build) (x86_64)
Firefox: 102.0 (64-bit) 
Safari: 15.5 (17613.2.7.1.8)
```

**Comment by Millali** [comment]
@secondmanveran I checked, and the issue happens when user tries to add two substances in the row.  It just happened on my end, and I have the Chrome version you listed.  Please watch the video below:
https://www.loom.com/share/0ade3d4af00d463f984ceb8ce00ccb55

**Comment by ChantalLavigne** [comment]
@secondmanveran 
@Millali 
Hi, I cannot add any substance.  I go through the add substance process and even if the system says it was a success, no substance is listed in my HPD. I have Chrome Version 103.0.5060.66 (Build officiel) (64 bits)

**Comment by Millali** [comment]
@secondmanveran 

This is not fixed. I have added geological materials 4 times in this record, and they don't show up after I save them. 
Please watch the video. 

https://www.loom.com/share/3951a8802a6846098b2f54203f1ffe82

Milla

https://stage.hpd-collaborative.org/actions/builder/7259/record

**Comment by secondmanveran** [comment]
@Millali 

I'm not sure what to tell you, it isn't something that can be fixed because it isn't broken.

I just added all 6 different types of special conditions, one after the other with no errors whatsoever.

<img width="899" alt="Screen Shot 2022-07-05 at 8 38 30 PM" src="https://user-images.githubusercontent.com/97000801/177463117-caf878a2-a891-48f9-a539-ccf40b093eda.png">

I can't fix what isn't broken.

See for yourself here:

https://stage.hpd-collaborative.org/actions/builder/7259/record

Obviously I want to help figure out what's wrong, but it's not a programming issue, it's a local issue with your browser or something else. 

Testing should always be done with the Inspector panel open so you can visualize any errors that are happening. I'm not seeing that in any of your testing videos. 

It could be possible that something is stuck in your cache, I really have no idea.

Try doing a hard reload which is available when the Inspector panel is open.

<img width="472" alt="Screen Shot 2022-07-05 at 8 45 05 PM" src="https://user-images.githubusercontent.com/97000801/177464047-b8faaf51-59f6-4ca6-b1dc-37208f923684.png">


```
Press F12 to open the Inspector panel
Press and hold the reload button to get the dropdown menu
Click Empty Cache and Hard Reload in the menu
Retry adding Materials
```

Also make sure your browser is up to date.

Barring this I can't spend anymore time on this, it's keeping me from finishing other issues.

**Comment by Millali** [comment]
@secondmanveran something must be happening that 4 people are reporting the same issue. While it is working for you, we need to find a way to support other users that are unable to save materials and continue testing, including myself. 

It just tested again and none of the SC entries work.  We can't sign off the testing for SC if we can't indeed test it. 

Milla

**Comment by Millali** [comment]
@secondmanveran 
I cleared off all my browser cache and I am still getting the same issue. 

Milla

**Comment by secondmanveran** [comment]
@Millali 

Without any further error information via the inspector or telescope I can't help any further. I cannot troubleshoot issues on personal machines.

The code works, period. 

As I said, make sure you're working with the Inspector panel open, watching for errors in the console and network panels, perhaps we can see something there.

**Comment by Millali** [comment]
Hi Vince, 

I tried adding substances with the console open. Here is the video

https://www.loom.com/share/a82b9593a07d417999fb1e11a8694a5c

And here is the error message I got: 

vue.esm.js:1906 TypeError: Cannot read properties of undefined (reading 'length')
    at o.hasHazards (SubstanceActions.vue:57:1)
    at se.get (vue.esm.js:4504:25)
    at se.evaluate (vue.esm.js:4606:21)
    at o.hasHazards (vue.esm.js:4860:17)
    at o.h (SubstanceActions.vue?vue&type=template&lang.js:1:1)
    at vue-composition-api.mjs:1942:35
    at Ie (vue-composition-api.mjs:1896:16)
    at f.render (vue-composition-api.mjs:1941:24)
    at e._render (vue.esm.js:3578:22)
    at o.n (vue.esm.js:4090:21)
wn @ vue.esm.js:1906
Sn @ vue.esm.js:1897
Re @ vue.esm.js:1857
e._render @ vue.esm.js:3580
n @ vue.esm.js:4090
se.get @ vue.esm.js:4504
se @ vue.esm.js:4493
co @ vue.esm.js:4097
D.$mount @ vue.esm.js:9107
D.$mount @ vue.esm.js:12023
init @ vue.esm.js:3146
d @ vue.esm.js:6033
c @ vue.esm.js:5980
T @ vue.esm.js:6108
c @ vue.esm.js:6009
(anonymous) @ vue.esm.js:6532
e._update @ vue.esm.js:3969
n @ vue.esm.js:4090
se.get @ vue.esm.js:4504
se @ vue.esm.js:4493
co @ vue.esm.js:4097
D.$mount @ vue.esm.js:9107
D.$mount @ vue.esm.js:12023
init @ vue.esm.js:3146
d @ vue.esm.js:6033
c @ vue.esm.js:5980
(anonymous) @ vue.esm.js:6532
e._update @ vue.esm.js:3969
n @ vue.esm.js:4090
se.get @ vue.esm.js:4504
se @ vue.esm.js:4493
co @ vue.esm.js:4097
D.$mount @ vue.esm.js:9107
D.$mount @ vue.esm.js:12023
init @ vue.esm.js:3146
d @ vue.esm.js:6033
c @ vue.esm.js:5980
T @ vue.esm.js:6108
c @ vue.esm.js:6009
(anonymous) @ vue.esm.js:6532
e._update @ vue.esm.js:3969
n @ vue.esm.js:4090
se.get @ vue.esm.js:4504
se @ vue.esm.js:4493
co @ vue.esm.js:4097
D.$mount @ vue.esm.js:9107
D.$mount @ vue.esm.js:12023
init @ vue.esm.js:3146
d @ vue.esm.js:6033
c @ vue.esm.js:5980
(anonymous) @ vue.esm.js:6532
e._update @ vue.esm.js:3969
n @ vue.esm.js:4090
se.get @ vue.esm.js:4504
se @ vue.esm.js:4493
co @ vue.esm.js:4097
D.$mount @ vue.esm.js:9107
D.$mount @ vue.esm.js:12023
init @ vue.esm.js:3146
d @ vue.esm.js:6033
c @ vue.esm.js:5980
A @ vue.esm.js:6161
oe @ vue.esm.js:6288
Y @ vue.esm.js:6374
(anonymous) @ vue.esm.js:6537
e._update @ vue.esm.js:3972
n @ vue.esm.js:4090
se.get @ vue.esm.js:4504
se.run @ vue.esm.js:4579
vo @ vue.esm.js:4335
(anonymous) @ vue.esm.js:1998
vt @ vue.esm.js:1924
Promise.then (async)
et @ vue.esm.js:1951
Wr @ vue.esm.js:2008
yo @ vue.esm.js:4427
se.update @ vue.esm.js:4569
Z.notify @ vue.esm.js:739
(anonymous) @ vue.esm.js:891
pl @ mutations.js:468
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
v._withCommit @ vuex.esm.js:624
v.commit @ vuex.esm.js:464
commit @ vuex.esm.js:409
Z.n.commit @ vuex.esm.js:796
(anonymous) @ actions.js:211
Promise.then (async)
ic @ actions.js:210
(anonymous) @ vuex.esm.js:851
v.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
r.<computed> @ vuex.esm.js:1064
saveSubstance @ SubstanceForm.vue:482
click @ SubstanceForm.vue?vue&type=template&lang.js:1
qe @ vue.esm.js:1872
r @ vue.esm.js:2197
Hf.a._wrapper @ vue.esm.js:7609
Show 42 more frames
vue.esm.js:1906 TypeError: Cannot read properties of undefined (reading 'length')
    at o.hasHazards (SubstanceActions.vue:57:1)
    at se.get (vue.esm.js:4504:25)
    at se.evaluate (vue.esm.js:4606:21)
    at o.hasHazards (vue.esm.js:4860:17)
    at o.h (SubstanceActions.vue?vue&type=template&lang.js:1:1)
    at vue-composition-api.mjs:1942:35
    at Ie (vue-composition-api.mjs:1896:16)
    at f.render (vue-composition-api.mjs:1941:24)
    at e._render (vue.esm.js:3578:22)
    at o.n (vue.esm.js:4090:21)
wn @ vue.esm.js:1906
Sn @ vue.esm.js:1897
Re @ vue.esm.js:1857
e._render @ vue.esm.js:3580
n @ vue.esm.js:4090
se.get @ vue.esm.js:4504
se.run @ vue.esm.js:4579
vo @ vue.esm.js:4335
(anonymous) @ vue.esm.js:1998
vt @ vue.esm.js:1924
Promise.then (async)
et @ vue.esm.js:1951
Wr @ vue.esm.js:2008
yo @ vue.esm.js:4427
se.update @ vue.esm.js:4569
Z.notify @ vue.esm.js:739
set @ vue.esm.js:1064
Qr._e.set @ vue.esm.js:4653
Cn @ order-by-column.js:10
click @ RLTableHeading.js:39
qe @ vue.esm.js:1872
r @ vue.esm.js:2197
Hf.a._wrapper @ vue.esm.js:7609

**Comment by secondmanveran** [comment]
@Millali @ChantalLavigne 

Great job, this gives me something to look for.

**Comment by ChantalLavigne** [comment]
@secondmanveran 
I tried.  Still not working form me.
![image](https://user-images.githubusercontent.com/107648303/177606179-70d65149-557e-4374-8a17-574beb3e88ee.png)

**Comment by vanduima** [comment]
I just tried and am getting the same issue.  Console log (attached too)
[stage.hpd-collaborative.org-1657165968244.log](https://github.com/HPDCollaborative/builder23review/files/9060219/stage.hpd-collaborative.org-1657165968244.log)
:

setProperties.js:66 
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
cr @ setProperties.js:66
oe @ setProperties.js:101
(anonymous) @ getCreateDomElement.js:27
So @ createAutocompleteDom.js:138
(anonymous) @ autocomplete.js:108
reactive @ createReactiveWrapper.js:5
$a @ autocomplete.js:107
mounted @ SubstancePalette.vue:31
qe @ vue.esm.js:1872
ie @ vue.esm.js:4244
insert @ vue.esm.js:3167
Ae @ vue.esm.js:6401
(anonymous) @ vue.esm.js:6620
e._update @ vue.esm.js:3972
n @ vue.esm.js:4090
se.get @ vue.esm.js:4504
se.run @ vue.esm.js:4579
vo @ vue.esm.js:4335
(anonymous) @ vue.esm.js:1998
vt @ vue.esm.js:1924

vue.esm.js:1906 
TypeError: Cannot read properties of undefined (reading 'length')
    at o.hasHazards (SubstanceActions.vue:58:1)
    at se.get (vue.esm.js:4504:25)
    at se.evaluate (vue.esm.js:4606:21)
    at o.hasHazards (vue.esm.js:4860:17)
    at o.h (SubstanceActions.vue?vue&type=template&lang.js:1:1)
    at vue-composition-api.mjs:1942:35
    at Ie (vue-composition-api.mjs:1896:16)
    at f.render (vue-composition-api.mjs:1941:24)
    at e._render (vue.esm.js:3578:22)
    at o.n (vue.esm.js:4090:21)

  | wn | @ | vue.esm.js:1906
  | Sn | @ | vue.esm.js:1897
  | Re | @ | vue.esm.js:1857
  | e._render | @ | vue.esm.js:3580
  | n | @ | vue.esm.js:4090
  | se.get | @ | vue.esm.js:4504
  | se | @ | vue.esm.js:4493
  | co | @ | vue.esm.js:4097
  | D.$mount | @ | vue.esm.js:9107
  | D.$mount | @ | vue.esm.js:12023
  | init | @ | vue.esm.js:3146
  | d | @ | vue.esm.js:6033
  | c | @ | vue.esm.js:5980
  | T | @ | vue.esm.js:6108
  | c | @ | vue.esm.js:6009
  | (anonymous) | @ | vue.esm.js:6532
  | e._update | @ | vue.esm.js:3969
  | n | @ | vue.esm.js:4090
  | se.get | @ | vue.esm.js:4504
  | se | @ | vue.esm.js:4493
  | co | @ | vue.esm.js:4097
  | D.$mount | @ | vue.esm.js:9107
  | D.$mount | @ | vue.esm.js:12023
  | init | @ | vue.esm.js:3146
  | d | @ | vue.esm.js:6033
  | c | @ | vue.esm.js:5980
  | (anonymous) | @ | vue.esm.js:6532
  | e._update | @ | vue.esm.js:3969
  | n | @ | vue.esm.js:4090
  | se.get | @ | vue.esm.js:4504
  | se | @ | vue.esm.js:4493
  | co | @ | vue.esm.js:4097
  | D.$mount | @ | vue.esm.js:9107
  | D.$mount | @ | vue.esm.js:12023
  | init | @ | vue.esm.js:3146
  | d | @ | vue.esm.js:6033
  | c | @ | vue.esm.js:5980
  | T | @ | vue.esm.js:6108
  | c | @ | vue.esm.js:6009
  | (anonymous) | @ | vue.esm.js:6532
  | e._update | @ | vue.esm.js:3969
  | n | @ | vue.esm.js:4090
  | se.get | @ | vue.esm.js:4504
  | se | @ | vue.esm.js:4493
  | co | @ | vue.esm.js:4097
  | D.$mount | @ | vue.esm.js:9107
  | D.$mount | @ | vue.esm.js:12023
  | init | @ | vue.esm.js:3146
  | d | @ | vue.esm.js:6033
  | c | @ | vue.esm.js:5980
  | (anonymous) | @ | vue.esm.js:6532
  | e._update | @ | vue.esm.js:3969
  | n | @ | vue.esm.js:4090
  | se.get | @ | vue.esm.js:4504
  | se | @ | vue.esm.js:4493
  | co | @ | vue.esm.js:4097
  | D.$mount | @ | vue.esm.js:9107
  | D.$mount | @ | vue.esm.js:12023
  | init | @ | vue.esm.js:3146
  | d | @ | vue.esm.js:6033
  | c | @ | vue.esm.js:5980
  | oe | @ | vue.esm.js:6271
  | Y | @ | vue.esm.js:6374
  | (anonymous) | @ | vue.esm.js:6537
  | e._update | @ | vue.esm.js:3972
  | n | @ | vue.esm.js:4090
  | se.get | @ | vue.esm.js:4504
  | se.run | @ | vue.esm.js:4579
  | vo | @ | vue.esm.js:4335
  | (anonymous) | @ | vue.esm.js:1998
  | vt | @ | vue.esm.js:1924
  | Promise.then (async) |   |  
  | et | @ | vue.esm.js:1951
  | Wr | @ | vue.esm.js:2008
  | yo | @ | vue.esm.js:4427
  | se.update | @ | vue.esm.js:4569
  | Z.notify | @ | vue.esm.js:739
  | (anonymous) | @ | vue.esm.js:891
  | pl | @ | mutations.js:468
  | (anonymous) | @ | vuex.esm.js:844
  | (anonymous) | @ | vuex.esm.js:466
  | (anonymous) | @ | vuex.esm.js:465
  | v._withCommit | @ | vuex.esm.js:624
  | v.commit | @ | vuex.esm.js:464
  | commit | @ | vuex.esm.js:409
  | Z.n.commit | @ | vuex.esm.js:796
  | (anonymous) | @ | actions.js:211
  | Promise.then (async) |   |  
  | ic | @ | actions.js:210
  | (anonymous) | @ | vuex.esm.js:851
  | v.dispatch | @ | vuex.esm.js:516
  | dispatch | @ | vuex.esm.js:406
  | r.<computed> | @ | vuex.esm.js:1064
  | saveSubstance | @ | SubstanceForm.vue:482
  | click | @ | SubstanceForm.vue?vu…=template&lang.js:1
  | qe | @ | vue.esm.js:1872
  | r | @ | vue.esm.js:2197
  | Hf.a._wrapper | @ | vue.esm.js:7609

**Comment by secondmanveran** [comment]
@vanduima 

As mentioned previously, empty cache and hard reload:

> Try doing a hard reload which is available when the Inspector panel is open.
> 
> <img alt="Screen Shot 2022-07-05 at 8 45 05 PM" width="472" src="https://user-images.githubusercontent.com/97000801/177464047-b8faaf51-59f6-4ca6-b1dc-37208f923684.png">
> 
> ```
> Press F12 to open the Inspector panel
> Press and hold the reload button to get the dropdown menu
> Click Empty Cache and Hard Reload in the menu
> Retry adding Materials
> ```

**Comment by vanduima** [comment]
No change.  Still facing the same issue:

vue.esm.js:1906 TypeError: Cannot read properties of undefined (reading 'length')
    at o.hasHazards (SubstanceActions.vue:58:1)
    at se.get (vue.esm.js:4504:25)
    at se.evaluate (vue.esm.js:4606:21)
    at o.hasHazards (vue.esm.js:4860:17)
    at o.h (SubstanceActions.vue?vue&type=template&lang.js:1:1)
    at vue-composition-api.mjs:1942:35
    at Ie (vue-composition-api.mjs:1896:16)
    at f.render (vue-composition-api.mjs:1941:24)
    at e._render (vue.esm.js:3578:22)
    at o.n (vue.esm.js:4090:21)

**Comment by secondmanveran** [comment]
This is a local issue with your browser, not an issue with the code. This was proven earlier today in a live zoom meeting so I know for a fact it resolves the issue.

I believe @Millali is preparing some instruction or video to help walk people through it until we can determine why the javascript and css is not being cache busted when it's updated.

**Comment by vanduima** [comment]
With all due respect, I don't think that's the case. I followed all the steps to hard upload in Chrome (Version 103.0.5060.114) and it's not working still, along with testing it extensively under different browser/OS conditions noted below.  The only thing that's coming to mind as a possibility since you're not seeing it but the rest of us are is the possibility of it being a permissions issue where your account has additional permissions allowing it to read the "undefined" items noted in the logs below.  I'm guessing I'm way off here, but I'm struggling to see why it would be working for you but not for the rest of us.  I'm happy to try more suggestions, but as you'll see below, I've tested everything I can think of to try and isolate the issue to a browser configuration.  Let me know if you have other thoughts.

I took additional steps to hard clear all cache from the browser, all site data/cookies from hpd-collaborative.org sites, and logged back in to see if that would fix things.  Logging in threw this error:
> lpfulllib.js:1 
> Uncaught DOMException: Blocked a frame with origin "chrome-extension://hdokiejnpimakedhajhdlcegeplioahd" from accessing a cross-origin frame.
>     at e [as constructor] (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/lpfulllib.js:1:1441203)
>     at new e (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/lpfulllib.js:1:1444389)
>     at chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/lpfulllib.js:1:1461175
> e @ lpfulllib.js:1
> e @ lpfulllib.js:1
> (anonymous) @ lpfulllib.js:1

I tried to add a substance again and it threw the same error as before:
> vue.esm.js:1906 TypeError: Cannot read properties of undefined (reading 'length')
>     at o.hasHazards (SubstanceActions.vue:58:1)
>     at se.get (vue.esm.js:4504:25)
>     at se.evaluate (vue.esm.js:4606:21)
>     at o.hasHazards (vue.esm.js:4860:17)
>     at o.h (SubstanceActions.vue?vue&type=template&lang.js:1:1)
>     at vue-composition-api.mjs:1942:35
>     at Ie (vue-composition-api.mjs:1896:16)
>     at f.render (vue-composition-api.mjs:1941:24)
>     at e._render (vue.esm.js:3578:22)
>     at o.n (vue.esm.js:4090:21)

Just in case it was a browser issue, I tested it in an ingonito window in Chrome and got the same error.  Furthermore, I tested it in Safari (version 15.4 17613.1.17.1.13( to see if it was a Chrome issue for me, and it has the same issue with a slightly different error code:

> vue.esm.js:1922
> [Error] TypeError: undefined is not an object (evaluating 'this.data.hazards.length')
> hasHazards — SubstanceActions.vue:58
> (anonymous function) — vue.esm.js:4509
> (anonymous function) — vue.esm.js:4616
> (anonymous function) — vue.esm.js:4872
> h — SubstanceActions.vue:1
> Ie — vue-composition-api.mjs:1896
> (anonymous function) — vue.esm.js:3595
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> se — vue.esm.js:4505
> co — vue.esm.js:4104
> init — vue.esm.js:3152
> d — vue.esm.js:6050
> c — vue.esm.js:6003
> T — vue.esm.js:6111
> c — vue.esm.js:6021
> (anonymous function) — vue.esm.js:6543
> (anonymous function) — vue.esm.js:3983
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> se — vue.esm.js:4505
> co — vue.esm.js:4104
> init — vue.esm.js:3152
> d — vue.esm.js:6050
> c — vue.esm.js:6003
> (anonymous function) — vue.esm.js:6543
> (anonymous function) — vue.esm.js:3983
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> se — vue.esm.js:4505
> co — vue.esm.js:4104
> init — vue.esm.js:3152
> d — vue.esm.js:6050
> c — vue.esm.js:6003
> T — vue.esm.js:6111
> c — vue.esm.js:6021
> (anonymous function) — vue.esm.js:6543
> (anonymous function) — vue.esm.js:3983
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> se — vue.esm.js:4505
> co — vue.esm.js:4104
> init — vue.esm.js:3152
> d — vue.esm.js:6050
> c — vue.esm.js:6003
> (anonymous function) — vue.esm.js:6543
> (anonymous function) — vue.esm.js:3983
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> se — vue.esm.js:4505
> co — vue.esm.js:4104
> init — vue.esm.js:3152
> d — vue.esm.js:6050
> c — vue.esm.js:6003
> oe — vue.esm.js:6277
> Y — vue.esm.js:6381
> (anonymous function) — vue.esm.js:6544
> (anonymous function) — vue.esm.js:3980
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> (anonymous function) — vue.esm.js:4592
> vo — vue.esm.js:4370
> (anonymous function) — vue.esm.js:2011
> vt — vue.esm.js:1950
> promiseReactionJob
> 
> 	wn (portal.f258da70.js:5:12144)
> 	Sn (portal.f258da70.js:5:12077)
> 	Re (portal.f258da70.js:5:11755)
> 	(anonymous function) (portal.f258da70.js:5:23944)
> 	n (portal.f258da70.js:5:27950)
> 	(anonymous function) (portal.f258da70.js:5:30822)
> 	se (portal.f258da70.js:5:30743)
> 	co (portal.f258da70.js:5:27963)
> 	init (portal.f258da70.js:5:20714)
> 	d (portal.f258da70.js:5:44628)
> 	c (portal.f258da70.js:5:44257)
> 	T (portal.f258da70.js:5:45238)
> 	c (portal.f258da70.js:5:44372)
> 	(anonymous function) (portal.f258da70.js:5:48779)
> 	(anonymous function) (portal.f258da70.js:5:27135)
> 	n (portal.f258da70.js:5:27940)
> 	(anonymous function) (portal.f258da70.js:5:30822)
> 	se (portal.f258da70.js:5:30743)
> 	co (portal.f258da70.js:5:27963)
> 	init (portal.f258da70.js:5:20714)
> 	d (portal.f258da70.js:5:44628)
> 	c (portal.f258da70.js:5:44257)
> 	(anonymous function) (portal.f258da70.js:5:48779)
> 	(anonymous function) (portal.f258da70.js:5:27135)
> 	n (portal.f258da70.js:5:27940)
> 	(anonymous function) (portal.f258da70.js:5:30822)
> 	se (portal.f258da70.js:5:30743)
> 	co (portal.f258da70.js:5:27963)
> 	init (portal.f258da70.js:5:20714)
> 	d (portal.f258da70.js:5:44628)
> 	c (portal.f258da70.js:5:44257)
> 	T (portal.f258da70.js:5:45238)
> 	c (portal.f258da70.js:5:44372)
> 	(anonymous function) (portal.f258da70.js:5:48779)
> 	(anonymous function) (portal.f258da70.js:5:27135)
> 	n (portal.f258da70.js:5:27940)
> 	(anonymous function) (portal.f258da70.js:5:30822)
> 	se (portal.f258da70.js:5:30743)
> 	co (portal.f258da70.js:5:27963)
> 	init (portal.f258da70.js:5:20714)
> 	d (portal.f258da70.js:5:44628)
> 	c (portal.f258da70.js:5:44257)
> 	(anonymous function) (portal.f258da70.js:5:48779)
> 	(anonymous function) (portal.f258da70.js:5:27135)
> 	n (portal.f258da70.js:5:27940)
> 	(anonymous function) (portal.f258da70.js:5:30822)
> 	se (portal.f258da70.js:5:30743)
> 	co (portal.f258da70.js:5:27963)
> 	init (portal.f258da70.js:5:20714)
> 	d (portal.f258da70.js:5:44628)
> 	c (portal.f258da70.js:5:44257)
> 	oe (portal.f258da70.js:5:46869)
> 	Y (portal.f258da70.js:5:47672)
> 	(anonymous function) (portal.f258da70.js:5:48826)
> 	(anonymous function) (portal.f258da70.js:5:27112)
> 	n (portal.f258da70.js:5:27940)
> 	(anonymous function) (portal.f258da70.js:5:30822)
> 	(anonymous function) (portal.f258da70.js:5:31554)
> 	vo (portal.f258da70.js:5:29767)
> 	(anonymous function) (portal.f258da70.js:5:12855)
> 	vt (portal.f258da70.js:5:12264)
> 	promiseReactionJob

Lastly, I have access to a PC (Windows 11) and tested it in Microsoft Edge (version 103.0.1264.49) and it is throwing the same error as my Chrome browser was:
> vue.esm.js:1906 
>        TypeError: Cannot read properties of undefined (reading 'length')
>     at o.hasHazards (SubstanceActions.vue:58:1)
>     at se.get (vue.esm.js:4504:25)
>     at se.evaluate (vue.esm.js:4606:21)
>     at o.hasHazards (vue.esm.js:4860:17)
>     at o.h (SubstanceActions.vue?vue&type=template&lang.js:1:1)
>     at vue-composition-api.mjs:1942:35
>     at Ie (vue-composition-api.mjs:1896:16)
>     at f.render (vue-composition-api.mjs:1941:24)
>     at e._render (vue.esm.js:3578:22)
>     at o.n (vue.esm.js:4090:21)
> wn @ vue.esm.js:1906

**Comment by secondmanveran** [comment]
@vanduima 

There are no permissions embedded in the javascript.

The error you've copied here is referencing the `hasHazards` computed property in the `SubstanceActions` component. This is what tells me for sure that you're using old cached files since that computed property was renamed and no longer exists in the current code.

I've added some more aggressive cache busting for all javascript and css. Give it a try now.

Maybe with another hard reload just to be sure.

**Comment by vanduima** [comment]
@secondmanveran, that's what I was guessing but figured I'd mention it in case something odd was happening there.

I've done the hard reload, cleared cache, and checked multiple browsers and no changes still. I can take a look in the morning again in case I missed something, but I'm at a loss why I'm not updating to the newly pushed code.  Everything I'm seeing is saying I've done it correctly, but still no changes.  Odd.  Thanks for the work on this and hopefully we'll get something figured out shortly.

**Comment by vanduima** [comment]
@secondmanveran, one thought that I just had. We're working from the staging server (stage.hpd-collaborative.org) and from the looks for your screenshot earlier, you're working from a localized implementation of the code (builder.test).  Could the problem be that the update you made was for the live implementation and it never was pushed to the staging server?  Sorry if this is a dumb question, but I'm trying to come up with any out-of-the-box things that could be causing this.

**Comment by vanduima** [comment]
@Millali I've tried this multiple times, including just now, and it's not working in multiple browsers.  Can you try adding a substance to that material you have and let me know if it works for you in the stage.hpd-collaborative.org server?

**Comment by Millali** [comment]
Hi Matt, 

Did you clear the cache in Chrome with the inspector open, and it didn't work? It is not the normal cache clearing, it must be done with the inspector open. 

Here is a video: 

https://www.loom.com/share/dc0f414dde694da292e3535782aebdb6

Milla

**Comment by vanduima** [comment]
Yep, I'm very familiar with these requirements and I have done the "Empty Cache and Hard Reload", I've done it in Ingotnito mode which doesn't store cache, and I've tested it in other browsers that haven't touched the staging server before meaning there is nothing saved (new computer).  Is the substance creation working for you @Millali.

**Comment by ChantalLavigne** [comment]
@secondmanveran 
@Millali 
Still not working for me either, even if I did the "empty cache and hard reload" before.
![image](https://user-images.githubusercontent.com/107648303/177807242-4af7b12a-f680-4c91-88ac-114a29c1fba5.png)

**Comment by secondmanveran** [comment]
@vanduima @ChantalLavigne 

Can you please right click on the stage website and select View Page Source copy the link(s) you see for css and javascript on lines 13, 14?

Thanks

**Comment by secondmanveran** [comment]
> @secondmanveran, one thought that I just had. We're working from the staging server (stage.hpd-collaborative.org) and from the looks for your screenshot earlier, you're working from a localized implementation of the code (builder.test). Could the problem be that the update you made was for the live implementation and it never was pushed to the staging server? Sorry if this is a dumb question, but I'm trying to come up with any out-of-the-box things that could be causing this.

@vanduima No worries Matt, I appreciate you.

The screenshot you referenced was just to show the reload menu. Deployments are all automated though Github Actions, so whenever new code is saved it's automatically built, tested and deployed to our servers.

Good looking out though.

**Comment by vanduima** [comment]
Lines 13 and 14, @secondmanveran 
<link rel="stylesheet" href="https://stage.hpd-collaborative.org/build/app.92531.css">
<script type="module" src="https://stage.hpd-collaborative.org/build/app.92531.js" defer></script>

**Comment by vanduima** [comment]
Possibly on my standard Chrome browser (LastPass as an example), but I tested in incognito without extensions, in Safari which has no extensions, and on a completely different system (new PC on Edge) with no extensions, all with the same error.  

Actually, after reading the Safari error closer (see below), it looks like it's referencing the `hazardsExist` computed property in the 'SubstanceActions.vue' component, which is different from the 'hasHazards' property I'm getting on Chrome. So I'm guessing Safari is referring to the correct new build, but it's still not working.  The only thing I can think of is that 'this.data.hazards' object isn't an array for me for some reason, meaning the 'length' property would return as undefined, ultimately making the >0 operator not work. But it's been a few years (or a decade...) since I really did any debugging in js, so I could be way off here.

> [Error] TypeError: undefined is not an object (evaluating 'this.data.hazards.length')
> hazardsExist — SubstanceActions.vue:58
> (anonymous function) — vue.esm.js:4509
> (anonymous function) — vue.esm.js:4616
> (anonymous function) — vue.esm.js:4872
> h — SubstanceActions.vue:1
> Ie — vue-composition-api.mjs:1896
> (anonymous function) — vue.esm.js:3595
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> se — vue.esm.js:4505
> co — vue.esm.js:4104
> init — vue.esm.js:3152
> d — vue.esm.js:6050
> c — vue.esm.js:6003
> T — vue.esm.js:6111
> c — vue.esm.js:6021
> (anonymous function) — vue.esm.js:6543
> (anonymous function) — vue.esm.js:3983
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> se — vue.esm.js:4505
> co — vue.esm.js:4104
> init — vue.esm.js:3152
> d — vue.esm.js:6050
> c — vue.esm.js:6003
> (anonymous function) — vue.esm.js:6543
> (anonymous function) — vue.esm.js:3983
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> se — vue.esm.js:4505
> co — vue.esm.js:4104
> init — vue.esm.js:3152
> d — vue.esm.js:6050
> c — vue.esm.js:6003
> T — vue.esm.js:6111
> c — vue.esm.js:6021
> (anonymous function) — vue.esm.js:6543
> (anonymous function) — vue.esm.js:3983
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> se — vue.esm.js:4505
> co — vue.esm.js:4104
> init — vue.esm.js:3152
> d — vue.esm.js:6050
> c — vue.esm.js:6003
> (anonymous function) — vue.esm.js:6543
> (anonymous function) — vue.esm.js:3983
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> se — vue.esm.js:4505
> co — vue.esm.js:4104
> init — vue.esm.js:3152
> d — vue.esm.js:6050
> c — vue.esm.js:6003
> oe — vue.esm.js:6277
> Y — vue.esm.js:6381
> (anonymous function) — vue.esm.js:6544
> (anonymous function) — vue.esm.js:3980
> n — vue.esm.js:4100
> (anonymous function) — vue.esm.js:4509
> (anonymous function) — vue.esm.js:4592
> vo — vue.esm.js:4370
> (anonymous function) — vue.esm.js:2011
> vt — vue.esm.js:1950
> promiseReactionJob
> 
> 	wn (portal.74106.js:5:12144)
> 	Sn (portal.74106.js:5:12077)
> 	Re (portal.74106.js:5:11755)
> 	(anonymous function) (portal.74106.js:5:23944)
> 	n (portal.74106.js:5:27950)
> 	(anonymous function) (portal.74106.js:5:30822)
> 	se (portal.74106.js:5:30743)
> 	co (portal.74106.js:5:27963)
> 	init (portal.74106.js:5:20714)
> 	d (portal.74106.js:5:44628)
> 	c (portal.74106.js:5:44257)
> 	T (portal.74106.js:5:45238)
> 	c (portal.74106.js:5:44372)
> 	(anonymous function) (portal.74106.js:5:48779)
> 	(anonymous function) (portal.74106.js:5:27135)
> 	n (portal.74106.js:5:27940)
> 	(anonymous function) (portal.74106.js:5:30822)
> 	se (portal.74106.js:5:30743)
> 	co (portal.74106.js:5:27963)
> 	init (portal.74106.js:5:20714)
> 	d (portal.74106.js:5:44628)
> 	c (portal.74106.js:5:44257)
> 	(anonymous function) (portal.74106.js:5:48779)
> 	(anonymous function) (portal.74106.js:5:27135)
> 	n (portal.74106.js:5:27940)
> 	(anonymous function) (portal.74106.js:5:30822)
> 	se (portal.74106.js:5:30743)
> 	co (portal.74106.js:5:27963)
> 	init (portal.74106.js:5:20714)
> 	d (portal.74106.js:5:44628)
> 	c (portal.74106.js:5:44257)
> 	T (portal.74106.js:5:45238)
> 	c (portal.74106.js:5:44372)
> 	(anonymous function) (portal.74106.js:5:48779)
> 	(anonymous function) (portal.74106.js:5:27135)
> 	n (portal.74106.js:5:27940)
> 	(anonymous function) (portal.74106.js:5:30822)
> 	se (portal.74106.js:5:30743)
> 	co (portal.74106.js:5:27963)
> 	init (portal.74106.js:5:20714)
> 	d (portal.74106.js:5:44628)
> 	c (portal.74106.js:5:44257)
> 	(anonymous function) (portal.74106.js:5:48779)
> 	(anonymous function) (portal.74106.js:5:27135)
> 	n (portal.74106.js:5:27940)
> 	(anonymous function) (portal.74106.js:5:30822)
> 	se (portal.74106.js:5:30743)
> 	co (portal.74106.js:5:27963)
> 	init (portal.74106.js:5:20714)
> 	d (portal.74106.js:5:44628)
> 	c (portal.74106.js:5:44257)
> 	oe (portal.74106.js:5:46869)
> 	Y (portal.74106.js:5:47672)
> 	(anonymous function) (portal.74106.js:5:48826)
> 	(anonymous function) (portal.74106.js:5:27112)
> 	n (portal.74106.js:5:27940)
> 	(anonymous function) (portal.74106.js:5:30822)
> 	(anonymous function) (portal.74106.js:5:31554)
> 	vo (portal.74106.js:5:29767)
> 	(anonymous function) (portal.74106.js:5:12855)
> 	vt (portal.74106.js:5:12264)
> 	promiseReactionJob

**Comment by vanduima** [comment]
So the previous error in the console is now gone, but there's a new issue that is still preventing me from adding a substance.  Nothing is showing up in the console, and Loom video here: https://www.loom.com/share/fe1a267d241f4bf8bf5f82b329b7626a

**Comment by secondmanveran** [comment]
@vanduima 

Not sure what to tell you Matt.

I just added a substance and material to that record, both on the first try, no errors at all.

When you make a video please ensure you have the inspector panel open so I can verify what's happening.

I appreciate you continuing to test.

Thanks

**Comment by Millali** [comment]
Hi Everyone!

@vanduima, @Elixir-Tara, @ChantalLavigne 

Would you please test adding substances and materials one more time? Vince just deployed some fixes/updates. 

Thank you again for your support!

Milla

**Comment by Elixir-Tara** [comment]
Hi Milla,

I'm able to add substances and SC Materials now... yay!!!

The problem I still see is that a Nested Material consisting only of a SC Material ("Material Data Element") doesn't register with the system as being compliant for LEED - says "No substances have been reported for (Nested Material)", although the substance still shows up on the Preview.

Thanks for all of your hard work on this!

Best,
Tara



Tara Blank, Ph.D.
Elixir Environmental

(360) 857-8341

ElixirEnvironmental.com<http://ElixirEnvironmental.com>



Confidentiality Notice: This e-mail transmission may contain confidential or legally privileged information that is intended only for the individual or entity named in the e-mail address. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, or reliance upon the contents of this e-mail is strictly prohibited. If you have received this e-mail transmission in error, please reply to the sender, so that proper delivery can be arranged, and then please delete the message from your Inbox. Thank you.

________________________________

**Comment by secondmanveran** [comment]
@ChantalLavigne I'll look into the first part, that shouldn't be happening. 

Substance notes are not required, so you wouldn't get a validation error. Only a compliance suggestion to add them.

**Comment by secondmanveran** [comment]
Whoops. Hmmm ... maybe there's another condition under which they are required. 

I'll check it out for you.
